import './global.css';
import { Providers } from './providers';
import Navbar from './components/Navbar';
import { Grid, GridItem } from '@chakra-ui/react';
import Sidebar from './components/Sidebar';

export const metadata = {
  title: 'Welcome to session-forge-fe',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <Grid templateColumns="repeat(6, 1fr)" bg="gray.50">
          {/* sidebar */}
          <GridItem
            as="aside"
            colSpan={{ base: 6, lg: 2, xl: 1 }}
            bg="purple.400"
            minHeight={{ lg: '100vh' }}
            p={{ base: '20px', lg: '30px' }}
          >
            <Sidebar />
          </GridItem>

          <GridItem
            as="main"
            colSpan={{ base: 6, lg: 4, xl: 5 }}
            p="40px"
          >
            <Navbar />
            {children}
          </GridItem>
        </Grid>
      </Providers>
      </body>
    </html>
  );
}
